apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: number-reverser-dev

resources:
  - namespace.yaml
  - ../../base
  - network-policy.yaml

patches:
  - path: deployment-patch.yaml

#images:
#  - name: number-reverser
#    newName: number-reverser
#    newTag: 1.0.1
